# Generated by Django 5.2.5 on 2025-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, db_column='ANIO', null=True)),
                ('mes', models.IntegerField(blank=True, db_column='MES', null=True)),
                ('ubigeo_hecho', models.IntegerField(blank=True, db_column='UBIGEO_HECHO', null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo_hecho', models.IntegerField(blank=True, db_column='UBIGEO_HECHO', null=True)),
                ('p_modalidades', models.TextField(blank=True, db_column='P_MODALIDADES', null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modalidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo_hecho', models.IntegerField(blank=True, db_column='UBIGEO_HECHO', null=True)),
                ('dist_hecho', models.TextField(blank=True, db_column='DIST_HECHO', null=True)),
                ('total_robos', models.BigIntegerField(blank=True, null=True)),
                ('nivel_riesgo', models.TextField()),
            ],
            options={
                'db_table': 'riesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(blank=True, db_column='MES', null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'temporal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo_hecho', models.IntegerField(blank=True, db_column='UBIGEO_HECHO', null=True)),
                ('dist_hecho', models.TextField(blank=True, db_column='DIST_HECHO', null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zonas',
                'managed': False,
            },
        ),
    ]
